### PR TITLE
Fix: account for large numbers on 32-bit systems

### LINKED ISSUE #73: Internal use of `Word` makes valid versions platform-specific
While reading the codebase I found the use of `Word` as the internal representation in almost all datatypes related to version numbers. Furthermore, the parser for e.g. the `PVP` type parses this `Word` directly and wraps in the `PVP` constructor: https://github.com/fosskers/versions/blob/b73ea75156cef409c4512ed074dda82b52c5e46e/Data/Versions.hs#L906-L907

This means that what constitutes a valid PVP version, according to the parser, will differ between 32-bit and 64-bit systems: on the former the maximum version number component will be `32^2-1` while for the latter it will `64^2-1`.

Is this indented behavior?

### PR DESCRIPTION
**Pull request by fosskers**
Fixes #73

### CODE REVIEW

File: Data/Versions.hs [hunk 1]
```diff
@@ -850,7 +850,20 @@ semver'' = SemVer <$> majorP <*> minorP <*> patchP <*> optional releaseP <*> opt
...
+
+    convertOrFail :: Word64 -> Parsec Void Text Word
+    convertOrFail w | w'' /= w = fail "You are not on a 64-bit system and have encountered a number too large to parse."
+                    | otherwise = pure w'
+      where
+        w' :: Word
+        w' = fromIntegral w
+
+        w'' :: Word64
+        w'' = fromIntegral w'
```
Comment (fosskers) [inline Data/Versions.hs:866]: When you call `fromIntegral` on a value too large for its target type, it gets truncated, not rolled over. So, it would become equal to the `maxBound` of whatever the target type is.

**Comment by fosskers** [comment]
One "bug" remains, but we could just consider it known limitation: it's not possible to parse numbers larger than `Word64`. They are automatically truncated by `megaparsec` down to `maxBound :: Word64`.

**Comment by runeksvendsen** [comment]
> One "bug" remains, but we could just consider it known limitation: it's not possible to parse numbers larger than `Word64`. They are automatically truncated by `megaparsec` down to `maxBound :: Word64`.

I think it makes sense to have an upper bound on the version integer so that we guarantee that the parser terminates. If we're parsing it as an `Integer` then the parser would continue indefinitely when fed an infinite sequence of digits, which I'm not convinced is useful — it can be used for a denial-of-service attack for example.

**Comment by fosskers** [comment]
In that case I'll mention the limitation in documentation and leave it at that.

**Comment by fosskers** [comment]
Released as `6.0.6`.
